;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-paren
        indent-for-tab-command
        keyboard-escape-quit
        lsp-ui-doc--handle-mouse-movement
        tab-region
        untab-region
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        mc/mark-next-lines
        mc/mark-previous-lines
        mouse-set-region
        save-buffers-kill-terminal
        vscp/C-d
        ))
