;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beatp-delete-left-to-boundary
	beatp-dwim-kill
	beatp-dwim-previous-line
	beatp-dwim-save
	beatp-right-to-boundary
	beginning-of-defun
	c-electric-brace
	c-electric-paren
	corfu-complete
	corfu-next
	corfu-quit
	end-of-defun
	haskell-indentation-common-electric-command
	indent-for-tab-command
	keyboard-escape-quit
	kill-region
	killer-yank
	lsp-ui-doc--handle-mouse-movement
	ryanmarcus/backward-kill-word
	shit
	tab-region
	untab-region
	vscp/delete-to-boundry-backward
	))

(setq mc/cmds-to-run-once
      '(
	beat+/select-word-or-next-match
	beatp-left-to-boundary
	beatp-select-around-word-or-next-match
	beatp-select-word-or-next-match
	consult-buffer
	corfu-previous
	counsel-M-x
	eglot
	make
	markdown-outdent-or-delete
	mc/mark-next-lines
	mc/mark-previous-lines
	mouse-set-region
	previous-buffer
	save-buffers-kill-terminal
	scroll-bar-toolkit-scroll
	vscp/C-d
	vscp/select-word-or-next-match
	))
